version: '3'
services:
  db:
    image: mysql:5
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "9999:80"
    depends_on:
      - db

  php:
    build: docker/php
    ports:
      - "8888:80"
    depends_on:
      - db
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www

  mailer:
    image: schickling/mailcatcher
    ports:
      - "1025:25"
      - "1080:1080"

  blackfire:
    image: blackfire/blackfire
    ports: [ "8707" ]
    environment:
      # Exposes BLACKFIRE_* environment variables from the host
      BLACKFIRE_SERVER_ID: $BLACKFIRE_SERVER_ID
      BLACKFIRE_SERVER_TOKEN: $BLACKFIRE_SERVER_TOKEN
      BLACKFIRE_CLIENT_ID: $BLACKFIRE_CLIENT_ID
      BLACKFIRE_CLIENT_TOKEN: $BLACKFIRE_CLIENT_TOKEN
